# Generated by Django 5.1.1 on 2024-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil')], default='USA', max_length=100),
        ),
    ]
